config/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/', include(('files.urls', 'files'), namespace='files')),
    path('', include(('users.urls', 'users'), namespace='users')),
]

files/urls.py
from telnetlib import DO
from django.urls import path
from .views import (
    ListCreateFiles, 
    ListCreateFolders, 
    RetrieveContentInFolder,
    RetrieveUpdateDestroyFile,
    RetrieveUpdateDestroyFolder,
    DownloadFile,
    ShareFile,
    ShareFolder,
    ListContentSharedWithMe,
    SearchFilesAndFolders
    )

urlpatterns = [
    path('files/', ListCreateFiles.as_view(), name="listcreatefiles"),
    path('files/<int:pk>', RetrieveUpdateDestroyFile.as_view(), name="retrieveupdatedestroyfile"),
    path('files/<int:pk>/download', DownloadFile.as_view(), name="downloadfile"),
    path('files/<int:pk>/share', ShareFile.as_view(), name="sharefile"),
    path('folders/', ListCreateFolders.as_view(), name="listcreatefolders"),
    path('folders/<int:pk>', RetrieveUpdateDestroyFolder.as_view(), name="retrieveupdatedestroyfolder"),
    path('folders/<int:pk>/content', RetrieveContentInFolder.as_view(), name="retrievefilesinfolder"),
    path('folders/<int:pk>/share', ShareFolder.as_view(), name="sharefolder"),
    path('shared-with-me/', ListContentSharedWithMe.as_view(), name='listcontentsharedwithme'),
    path('search/', SearchFilesAndFolders.as_view(), name='search')
]

users/urls.py
from django.urls import path
from .views import SignUpView, RetrieveUpdateView

urlpatterns = [
    path('signup', SignUpView.as_view(), name="signupview"),
    path('my-profile', RetrieveUpdateView.as_view(), name="retrieveupdateview"),
]

users/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser



class SignupForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

class EditForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

users/views.py
from rest_framework import generics
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated

from django.contrib.auth import get_user_model
from .serializers import UserSerializer
from .models import CustomUser
from files.models import Folder


class SignUpView(generics.CreateAPIView):
    permission_classes = []
    serializer_class = UserSerializer
    queryset = CustomUser.objects.all()

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        print(request.data)
        
        user = get_user_model().objects.create_user(
                    email=serializer.data['email'],
                    password=request.data['password']
                    )
        
        root_folder = Folder(
            folder_name='root',
            color='#FAFAFA',
            root_folder=True,
            owner=user
        )
        root_folder.save()

        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, headers=headers)

class RetrieveUpdateView(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = [IsAuthenticated]
    serializer_class = UserSerializer

    def get_object(self):
        return CustomUser.objects.get(id=self.request.user.id)

users/templates/users/loggedout.html
<html>
  {% include "urlshortner/header.html" %}
  <div class="centralSection">
    <h1 class="colored">You have been successfully logged out</h1>
    <a href="{% url 'urlshortner:shortenlinkview' %}" class="btn">
      Go back to the app
    </a>
  </div>
</html>

users/templates/users/login.html
<html>
  {% include "urlshortner/header.html" %} {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li>
      {% if message.tags %}
      <span class="{{ message.tags }}">{% endif %}{{ message }}</span>
    </li>
    {% endfor %}
  </ul>
  {% endif %}
  <div class="centralSection">
    <h1 class="colored">Fill up the form to log in</h1>
    <form action="{% url 'users:loginview' %}" method="post">
      {% csrf_token %} {{ form }}
      <input type="submit" value="Submit" />
    </form>
  </div>
</html>

users/templates/users/settings.html
<html>
  {% include "urlshortner/header.html" %} {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li>
      {% if message.tags %}
      <span class="{{ message.tags }}">{% endif %}{{ message }}</span>
    </li>
    {% endfor %}
  </ul>
  {% endif %}
  <div class="centralSection">
    <h1 class="colored">Settings & Profile</h1>
    <form method="post">
      {% csrf_token %} {{ form.as_p }}
      <input type="submit" value="Save" />
    </form>
  </div>
</html>

users/templates/users/signup.html
<html>
  {% include "urlshortner/header.html" %}
  <div class="centralSection">
    <h1 class="colored">Fill up the form to sign up</h1>
    <form action="{% url 'users:signupview' %}" method="post">
      {% csrf_token %} {{ form }}
      <input type="submit" value="Submit" />
    </form>
  </div>
</html>